version: "3.9"
services:
  drawer:
    build: .
    restart: always
    ports:
    - 1000:1000
    volumes:
    - ./api/src/config.js:/work/api/config.js
    entrypoint: "node app"
    extra_hosts:
    - "host.docker.internal:host-gateway"